import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_test: String = "org.jetbrains.kotlinx:kotlinx-coroutines-test:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_preference: String =
            "io.github.reactivecircus.flowbinding:flowbinding-preference:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_swiperefreshlayout: String =
            "io.github.reactivecircus.flowbinding:flowbinding-swiperefreshlayout:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_activity: String =
            "io.github.reactivecircus.flowbinding:flowbinding-activity:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_android: String =
            "io.github.reactivecircus.flowbinding:flowbinding-android:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_appcompat: String =
            "io.github.reactivecircus.flowbinding:flowbinding-appcompat:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_core: String = "io.github.reactivecircus.flowbinding:flowbinding-core:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_drawerlayout: String =
            "io.github.reactivecircus.flowbinding:flowbinding-drawerlayout:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_lifecycle: String =
            "io.github.reactivecircus.flowbinding:flowbinding-lifecycle:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_material: String =
            "io.github.reactivecircus.flowbinding:flowbinding-material:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_navigation: String =
            "io.github.reactivecircus.flowbinding:flowbinding-navigation:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_recyclerview: String =
            "io.github.reactivecircus.flowbinding:flowbinding-recyclerview:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/reactivecircus/FlowBinding
     */
    const val flowbinding_viewpager2: String =
            "io.github.reactivecircus.flowbinding:flowbinding-viewpager2:" +
            Versions.io_github_reactivecircus_flowbinding

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_permissions: String = "com.tailoredapps.androidutil:util-permissions:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_ui: String = "com.tailoredapps.androidutil:util-ui:" +
            Versions.com_tailoredapps_androidutil

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
            Versions.com_squareup_leakcanary

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_object_watcher_android: String =
            "com.squareup.leakcanary:leakcanary-object-watcher-android:" +
            Versions.com_squareup_leakcanary

    /**
     * https://developer.android.com/testing
     */
    const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:" +
            Versions.androidx_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
            Versions.androidx_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val espresso_intents: String = "androidx.test.espresso:espresso-intents:" +
            Versions.androidx_test_espresso

    /**
     * https://github.com/square/retrofit/
     */
    const val converter_gson: String = "com.squareup.retrofit2:converter-gson:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" +
            Versions.com_squareup_retrofit2

    /**
     * https://square.github.io/okhttp/
     */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.com_squareup_okhttp3

    /**
     * https://square.github.io/okhttp/
     */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:" + Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val lifecycle_viewmodel_ktx: String = "androidx.lifecycle:lifecycle-viewmodel-ktx:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_core: String = "androidx.test:core:" + Versions.androidx_test

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_rules: String = "androidx.test:rules:" + Versions.androidx_test

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test

    const val koin_android: String = "org.koin:koin-android:" + Versions.org_koin

    const val koin_androidx_scope: String = "org.koin:koin-androidx-scope:" + Versions.org_koin

    const val koin_androidx_viewmodel: String = "org.koin:koin-androidx-viewmodel:" +
            Versions.org_koin

    const val koin_core: String = "org.koin:koin-core:" + Versions.org_koin

    const val koin_test: String = "org.koin:koin-test:" + Versions.org_koin

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:" +
            Versions.androidx_test_ext_junit

    /**
     * http://junit.org
     */
    const val junit_junit: String = "junit:junit:" + Versions.junit_junit

    const val de_fayard_refreshversions_gradle_plugin: String =
            "de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin:" +
            Versions.de_fayard_refreshversions_gradle_plugin

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    const val ktlint_gradle: String = "org.jlleitschuh.gradle:ktlint-gradle:" +
            Versions.ktlint_gradle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val activity_ktx: String = "androidx.activity:activity-ktx:" + Versions.activity_ktx

    /**
     * https://github.com/floschu/control
     */
    const val control_core: String = "at.florianschuster.control:control-core:" +
            Versions.control_core

    /**
     * https://github.com/akaita/easylauncher-gradle-plugin
     */
    const val easylauncher: String = "com.akaita.android:easylauncher:" + Versions.easylauncher

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val fragment_ktx: String = "androidx.fragment:fragment-ktx:" + Versions.fragment_ktx

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://github.com/JakeWharton/ThreeTenABP/
     */
    const val threetenabp: String = "com.jakewharton.threetenabp:threetenabp:" +
            Versions.threetenabp

    const val viewbinding: String = "androidx.databinding:viewbinding:" + Versions.viewbinding

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val viewpager2: String = "androidx.viewpager2:viewpager2:" + Versions.viewpager2

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val browser: String = "androidx.browser:browser:" + Versions.browser

    /**
     * https://github.com/pinterest/ktlint
     */
    const val ktlint: String = "com.pinterest:ktlint:" + Versions.ktlint

    /**
     * https://github.com/JakeWharton/timber
     */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * http://mockk.io
     */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * https://github.com/coil-kt/coil
     */
    const val coil: String = "io.coil-kt:coil:" + Versions.coil

    /**
     * https://github.com/google/gson
     */
    const val gson: String = "com.google.code.gson:gson:" + Versions.gson
}
