import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val fragment_testing: String = "androidx.fragment:fragment-testing:_"

    const val lifecycle_runtime_testing: String = "androidx.lifecycle:lifecycle-runtime-testing:_"

    const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:_"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    const val espresso_intents: String = "androidx.test.espresso:espresso-intents:_"

    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    const val androidx_test_core: String = "androidx.test:core:_"

    const val androidx_test_rules: String = "androidx.test:rules:_"

    const val androidx_test_runner: String = "androidx.test:runner:_"

    const val control_core: String = "at.florianschuster.control:control-core:_"

    const val loco_core: String = "at.florianschuster.loco:loco-core:_"

    const val easylauncher: String = "com.akaita.android:easylauncher:_"

    const val gson: String = "com.google.code.gson:gson:_"

    const val util_permissions: String = "com.tailoredapps.androidutil:util-permissions:_"

    const val util_ui: String = "com.tailoredapps.androidutil:util-ui:_"

    const val coil: String = "io.coil-kt:coil:_"

    const val flowbinding_activity: String = "io.github.reactivecircus.flowbinding:flowbinding-activity:_"

    const val flowbinding_android: String = "io.github.reactivecircus.flowbinding:flowbinding-android:_"

    const val flowbinding_appcompat: String = "io.github.reactivecircus.flowbinding:flowbinding-appcompat:_"

    const val flowbinding_core: String = "io.github.reactivecircus.flowbinding:flowbinding-core:_"

    const val flowbinding_drawerlayout: String = "io.github.reactivecircus.flowbinding:flowbinding-drawerlayout:_"

    const val flowbinding_lifecycle: String = "io.github.reactivecircus.flowbinding:flowbinding-lifecycle:_"

    const val flowbinding_material: String = "io.github.reactivecircus.flowbinding:flowbinding-material:_"

    const val flowbinding_navigation: String = "io.github.reactivecircus.flowbinding:flowbinding-navigation:_"

    const val flowbinding_preference: String = "io.github.reactivecircus.flowbinding:flowbinding-preference:_"

    const val flowbinding_recyclerview: String = "io.github.reactivecircus.flowbinding:flowbinding-recyclerview:_"

    const val flowbinding_swiperefreshlayout: String = "io.github.reactivecircus.flowbinding:flowbinding-swiperefreshlayout:_"

    const val flowbinding_viewpager2: String = "io.github.reactivecircus.flowbinding:flowbinding-viewpager2:_"

    const val mockk: String = "io.mockk:mockk:_"

    const val junit_junit: String = "junit:junit:_"

    const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:_"

    const val kotlinx_coroutines_test: String = "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    const val koin_android: String = "org.koin:koin-android:_"

    const val koin_androidx_fragment: String = "org.koin:koin-androidx-fragment:_"

    const val koin_androidx_scope: String = "org.koin:koin-androidx-scope:_"

    const val koin_androidx_viewmodel: String = "org.koin:koin-androidx-viewmodel:_"

    const val koin_core: String = "org.koin:koin-core:_"

    const val koin_test: String = "org.koin:koin-test:_"
}
