import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val com_tailoredapps_androidutil: String = "16"

    const val com_jakewharton_rxbinding3: String = "3.1.0"

    const val com_squareup_leakcanary: String = "2.1"

    const val androidx_test_espresso: String = "3.2.0"

    const val com_squareup_retrofit2: String = "2.7.1"

    const val com_squareup_okhttp3: String = "4.3.1"

    const val org_jetbrains_kotlin: String = "1.3.61"

    const val androidx_navigation: String = "2.2.0"

    const val androidx_lifecycle: String = "2.2.0"

    const val androidx_test: String = "1.2.0"

    const val org_koin: String = "2.0.1"

    const val com_android_tools_build_gradle: String = "3.5.3"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val junit_junit: String = "4.13"

    const val de_fayard_refreshversions_gradle_plugin: String = "0.7.0" // available: "0.8.6"

    const val reaktor_android_koin: String = "1.1.0"

    const val constraintlayout: String = "1.1.3"

    const val ktlint_gradle: String = "9.1.1"

    const val activity_ktx: String = "1.1.0"

    const val easylauncher: String = "1.3.1"

    const val fragment_ktx: String = "1.2.0"

    const val lint_gradle: String = "26.5.3"

    const val threetenabp: String = "1.2.2"

    const val appcompat: String = "1.1.0"

    const val rxandroid: String = "2.1.1"

    const val core_ktx: String = "1.2.0-beta01"

    const val material: String = "1.2.0-alpha01"

    const val rxkotlin: String = "2.4.0"

    const val browser: String = "1.2.0"

    const val rxrelay: String = "2.1.1"

    const val ktlint: String = "0.35.0" // available: "0.36.0"

    const val rxjava: String = "2.2.17"

    const val timber: String = "4.7.1"

    const val aapt2: String = "3.5.3-5435860"

    const val mockk: String = "1.9.3"

    const val coil: String = "0.9.2"

    const val gson: String = "2.8.6"

    /**
     * Current version: "6.1.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.1.1"
}
