import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.5"

    const val io_github_reactivecircus_flowbinding: String = "0.9.0"

    const val com_tailoredapps_androidutil: String = "16"

    const val com_squareup_leakcanary: String = "2.2"

    const val androidx_test_espresso: String = "3.2.0"

    const val com_squareup_retrofit2: String = "2.7.2"

    const val com_squareup_okhttp3: String = "4.4.1"

    const val org_jetbrains_kotlin: String = "1.3.70"

    const val androidx_navigation: String = "2.2.1"

    const val androidx_lifecycle: String = "2.2.0"

    const val androidx_test: String = "1.2.0"

    const val org_koin: String = "2.1.4"

    const val com_android_tools_build_gradle: String = "3.6.1"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val junit_junit: String = "4.13"

    const val de_fayard_refreshversions_gradle_plugin: String = "0.7.0" // available: "0.9.3"

    const val constraintlayout: String = "1.1.3"

    const val ktlint_gradle: String = "9.2.1"

    const val activity_ktx: String = "1.1.0"

    const val control_core: String = "0.7.1"

    const val easylauncher: String = "1.3.1"

    const val fragment_ktx: String = "1.2.3"

    const val lint_gradle: String = "26.6.1"

    const val threetenabp: String = "1.2.2"

    const val viewpager2: String = "1.0.0"

    const val appcompat: String = "1.1.0"

    const val core_ktx: String = "1.2.0"

    const val material: String = "1.2.0-alpha01"

    const val browser: String = "1.2.0"

    const val ktlint: String = "0.36.0"

    const val timber: String = "4.7.1"

    const val aapt2: String = "3.6.1-6040484"

    const val mockk: String = "1.9.3"

    const val coil: String = "0.9.5"

    const val gson: String = "2.8.6"

    /**
     * Current version: "6.2.2"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.2.2"
}
